CREATE DATABASE QUANLYNHANVIEN

CREATE TABLE NHANVIEN
{
	MANV INT IDENTITY(1,1) PRIMARY KEY,
	MAPHONG VARCHAR(6),
	MALUONG VARCHAR(8),
	HOTEN NVARCHAR(70),
	NGAYSINH DATETIME,
	GIOITINH NVARCHAR(3),
	TTHONNHAN NVARCHAR(12),
	CMND/CCCD VARCHAR(12),
	NOICAP NVARCHAR(20),
	CHUCVU NVARCHAR(25),
	MALOAINV VARCHAR(10),
	LOAIHD NVARCHAR(20),
	THOIGIAN INT,
	NGAYKY DATETIME,
	NGAYHETHAN DATETIME,
	SDT VARCHAR(10),
	HOCVAN NVARCHAR(20),
	GHICHI NVARCHAR(60)
}

CREATE TABLE LOAINHANVIEN
{
	MALOAINV VARCHAR(10) PRIMARY KEY,
	TENLOAINV NVARCHAR(30),
	MUCLUONGCOBAN MONEY,
}

CREATE TABLE PHONGBAN
{
	MAPHONG VARCHAR(6) PRIMARY KEY,
	MABP VARCHAR(8),
	TENPHONG NVARCHAR(20),
	NGAYTHANHLAP DATETIME,
	GHICHU NVARCHAR(70)
}

CREATE TABLE BOPHAN
{
	MABP VARCHAR(8) PRIMARY KEY,
	TENBOPHAN NVARCHAR(20),
	NGAYTHANHLAP DATETIME,
	GHICHU NVARCHAR(70)
}

CREATE TABLE HOSOTHUVIEC
{
	MANVTV INT IDENTITY(1,1) PRIMARY KEY,
	HOTEN NVARCHAR(70),
	NGAYSINH DATETIME,
	GIOITINH NVARCHAR(3),
	CMND/CCCD VARCHAR(12),
	NOICAP NVARCHAR(20),
	VITRITHUVIEC NVARCHAR(25),
	NGAYTV DATETIME,
	SOTHANGTV INT,
	SDT VARCHAR(10),
	HOCVAN NVARCHAR(20),
	GHICHI NVARCHAR(60)
}

CREATE TABLE BANGCHAMCONGTHUVIEC
{
	MANVTV INT,
	THANG INT,
	NAM INT,
	PRIMARY KEY (MANVTV, THANG,NAM)
	SONGAYCONG INT,
	SONGAYNGHI INT,
	SOGIOLAMTHEM INT,
	LUONGTV MONEY,
	GHICHU NVARCHAR(60)
}

CREATE TABLE BANGCHAMCONG
{
	MANV INT,
	THANG INT,
	NAM INT,
	PRIMARY KEY (MANV, THANG,NAM),
	MALUONG VARCHAR(8),
	MAKT INT,
	MAKL INT,
	SONGAYCONG INT,
	SONGAYNGHI INT,
	SOGIOLAMTHEM INT,
	GHICHU NVARCHAR(60)
}

CREATE TABLE KHENTHUONG
{
	MAKT INT PRIMARY KEY,
	LYDO NVARCHAR(50)
}

CREATE TABLE KYLUAT
{
	MAKL INT PRIMARY KEY,
	LYDO NVARCHAR(50)
}

CREATE TABLE BANGLUONG
{
	MALUONG VARCHAR(8) PRIMARY KEY,
	LCB MONEY,
	PHUCAPCHUCVU MONEY,
	PHUCAPKHAC MONEY,
	GHICHU NVARCHAR(80)
}

CREATE TABLE THAYDOIBANGLUONG
{
	MANV INT,
	MALUONG VARCHAR(8),
	MALUONGMOI VARCHAR(8),
	PRIMARY KEY (MANV,MALUONG,MALUONGMOI),
	NGAYSUA DATETIME,
	LYDO NVARCHAR(70)
}

CREATE TABLE SOBH
{
	MABH INT IDENTITY(1,1) PRIMARY KEY,
	MANV INT,
	NGAYCAPSO DATETIME,
	NOICAPSO NVARCHAR(20),
	GHICHU NVARCHAR(70),
}

CREATE TABLE SOTHAISAN
{
	MATS INT IDENTITY(1,1) PRIMARY KEY,
	MANV INT,
	NGAYVESOM DATETIME,
	NGAYNGHISINH DATETIME,
	NGAYLAMTROLAI DATETIME,
	TROCAPCTY MONEY
	GHICHU NVARCHAR(70)
}

CREATE TABLE NVTHOIVIEC
{
	MANV INT PRIMARY KEY,
	HOTEN NVARCHAR(70),
	CMND/CCCD VARCHAR(12),
	NGAYTHOIVIEC DATETIME,
	LYDO NVARCHAR(50)
}

CREATE TABLE TAIKHOAN
(
	MATK INT IDENTITY(1,1) PRIMARY KEY,
	MALOAITK INT,
	TENCHUTAIKHOAN NVARCHAR(20),
	TENDANGNHAP VARCHAR(20),
	MATKHAU VARCHAR(90),
)

CREATE TABLE PHANLOAITAIKHOAN
(
	MALOAITK INT IDENTITY(1,1) PRIMARY KEY,
	TENLOAITK NVARCHAR(20),
	QUYENHAN NVARCHAR(50)
)

CREATE TABLE THAMSO
{
	MATHAMSO VARCHAR(4),
	TENTHAMSO NVARCHAR(20),
	GIATRI FLOAT
}
ALTER TABLE TAIKHOAN ADD CONSTRAINT FK_TAIKHOAN_MALOAITK FOREIGN KEY (MALOAITK) REFERENCES PHANLOAITAIKHOAN(MALOAITK)

INSERT INTO PHANLOAITAIKHOAN(TENLOAITK,QUYENHAN) VALUES ('Quản trị viên','mọi thứ')
INSERT INTO TAIKHOAN(MALOAITK,TENCHUTAIKHOAN,TENDANGNHAP,MATKHAU) VALUES (1,'ADMIN','ADMIN','6b86b273ff34fce19d6b804eff5a3f5747ada4eaa22f1d49c01e52ddb7875b4b')
